# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Device(_Embedded):
    _type = "device"
    _icon_dir = "resources/embedded/device"


class Camera(_Device):
    _icon = "camera.png"


class Camera_Dome(_Device):
    _icon = "camera_dome.png"


class Camera_Dome2(_Device):
    _icon = "camera_dome2.png"


class Client(_Device):
    _icon = "client.png"


class Gauge(_Device):
    _icon = "gauge.png"


class Gpio_Pins(_Device):
    _icon = "gpio_pins.png"


class Gpio_Pins2(_Device):
    _icon = "gpio_pins2.png"


class Printer(_Device):
    _icon = "printer.png"


class Rtc(_Device):
    _icon = "rtc.png"


class ServerCluster(_Device):
    _icon = "server-cluster.png"


class Server(_Device):
    _icon = "server.png"


class Tablet(_Device):
    _icon = "tablet.png"


class Wakeup(_Device):
    _icon = "wakeup.png"


# Aliases
