# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Device(_Embedded):
    _type = "device"
    _icon_dir = "resources/embedded/device"


class Camera(_Device):
    _icon = "camera.png"


class Camera_Dome(_Device):
    _icon = "camera_dome.png"


class Printer(_Device):
    _icon = "printer.png"


class ServerCluster(_Device):
    _icon = "server-cluster.png"


class Server(_Device):
    _icon = "server.png"


class Tablet(_Device):
    _icon = "tablet.png"


# Aliases
