# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Devtools(_Embedded):
    _type = "devtools"
    _icon_dir = "resources/embedded/devtools"


class Bug(_Devtools):
    _icon = "bug.png"


class Conversation(_Devtools):
    _icon = "conversation.png"


class Fingerprint(_Devtools):
    _icon = "fingerprint.png"


class Inspect2(_Devtools):
    _icon = "inspect2.png"


class Tree(_Devtools):
    _icon = "tree.png"


class XML(_Devtools):
    _icon = "xml.png"


# Aliases
