# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _General(_Embedded):
    _type = "general"
    _icon_dir = "diagrams/resources/embedded/general"


class Cog(_General):
    _icon = "cog.png"


class Communications(_General):
    _icon = "communications.png"


class Grid(_General):
    _icon = "grid.png"


class Grid2(_General):
    _icon = "grid2.png"


class Link(_General):
    _icon = "link.png"


class Pinpoint(_General):
    _icon = "pinpoint.png"


class Scull(_General):
    _icon = "scull.png"


# Aliases
