# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Identity(_Embedded):
    _type = "identity"
    _icon_dir = "resources/embedded/identity"


class Ldap(_Identity):
    _icon = "ldap.png"


# Aliases
