# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Network(_Embedded):
    _type = "network"
    _icon_dir = "resources/embedded/network"


class Cloud(_Network):
    _icon = "cloud.png"


class Dslam(_Network):
    _icon = "dslam.png"


class Firewall(_Network):
    _icon = "firewall.png"


class Hub(_Network):
    _icon = "hub.png"


class Interconnect(_Network):
    _icon = "interconnect.png"


class ISDN(_Network):
    _icon = "isdn.png"


class Loadbalancer(_Network):
    _icon = "loadbalancer.png"


class Rj45(_Network):
    _icon = "rj45.png"


class Router(_Network):
    _icon = "router.png"


class Satellite(_Network):
    _icon = "satellite.png"


class Switch(_Network):
    _icon = "switch.png"


class Switch_Multilayer(_Network):
    _icon = "switch_multilayer.png"


class Wifi(_Network):
    _icon = "wifi.png"


class WLC(_Network):
    _icon = "wlc.png"


# Aliases
