# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Place(_Embedded):
    _type = "place"
    _icon_dir = "resources/embedded/place"


class House(_Place):
    _icon = "house.png"


class Office(_Place):
    _icon = "office.png"


# Aliases
