# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Security(_Embedded):
    _type = "security"
    _icon_dir = "diagrams/resources/embedded/security"


class Padlock(_Security):
    _icon = "padlock.png"


class Padlock_Open(_Security):
    _icon = "padlock_open.png"


class Shield(_Security):
    _icon = "shield.png"


# Aliases
