# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _Storage(_Embedded):
    _type = "storage"
    _icon_dir = "diagrams/resources/embedded/storage"


class Flash(_Storage):
    _icon = "flash.png"


class NAS(_Storage):
    _icon = "nas.png"


class Storage(_Storage):
    _icon = "storage.png"


# Aliases
