# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _User(_Embedded):
    _type = "user"
    _icon_dir = "diagrams/resources/embedded/user"


class User(_User):
    _icon = "user.png"


# Aliases
