# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Embedded


class _User(_Embedded):
    _type = "user"
    _icon_dir = "resources/embedded/user"


class Client(_User):
    _icon = "client.png"


class User(_User):
    _icon = "user.png"


# Aliases
